name: Python CI/CD

# Trigger the workflow on push or pull_request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.runner }}  # Dynamically selects the runner based on matrix

    strategy:
      matrix:
        runner: [self-hosted, ubuntu-latest]  # Matrix with both runners
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pyenv and Python 3.9
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y make build-essential libssl-dev zlib1g-dev
          
          # Install pyenv
          curl https://pyenv.run | bash

          # Add pyenv to the shell path
          echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
          
          # Restart shell to update PATH
          source $GITHUB_ENV

          # Install Python 3.9 using pyenv
          pyenv install 3.9.10
          pyenv global 3.9.10

      - name: Verify Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover