name: CI Pipeline

# Trigger the workflow when code is pushed to the main branch or when pull requests are made
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js (assuming a Node.js project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests (assuming tests are in the 'test' folder)
      - name: Run Tests
        run: npm test

  # Job to deploy the app (optional, here it's just a placeholder)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # This job will only run if the test job passes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Add deployment steps (e.g., deploying to AWS, Heroku, etc.)
      - name: Deploy Application
        run: echo "Deploying application..."
