name: Python CI/CD

# Trigger the workflow on push or pull_request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p playbooks'
  test:
    runs-on: ${{ matrix.runner }}  # Dynamically selects the runner based on matrix

    strategy:
      matrix:
        runner: [self-hosted, ubuntu-latest]  # Matrix with both runners
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up pyenv
        run: |
          curl https://pyenv.run | bash
          echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $HOME/.bashrc
          echo 'eval "$(pyenv init --path)"' >> $HOME/.bashrc
          echo 'eval "$(pyenv init -)"' >> $HOME/.bashrc
          source $HOME/.bashrc
        shell: bash

      - name: Install Python version
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          pyenv install 3.9.1
          pyenv global 3.9.1

      - name: Verify Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover